(require 'quelpa (locate-user-emacs-file "site-lisp/quelpa/quelpa"))

(package-initialize)

(quelpa 'exec-path-from-shell)
(exec-path-from-shell-initialize)

(quelpa 'ac-c-headers)
(quelpa 'async)
(quelpa 'auctex)
(quelpa 'auto-complete)
(quelpa 'bind-key)
(quelpa 'clang-format)
(quelpa 'dash)
(quelpa 'diminish)
(quelpa 'drag-stuff)
(quelpa 'edit-indirect)
(quelpa 'ess)
(quelpa 'exec-path-from-shell)
(quelpa 'expand-region)
(quelpa 'f)
(quelpa 'flycheck)
(quelpa 'flycheck-objc-clang)
(quelpa 'flycheck-pos-tip)
(quelpa 'ggtags)
(quelpa 'git-commit)
(quelpa 'htmlize)
(quelpa 'hungry-delete)
(quelpa 'idle-highlight-mode)
(quelpa 'js2-mode)
(quelpa 'julia-mode)
(quelpa 'magit)
(quelpa 'magit-popup)
(quelpa 'multiple-cursors)
(quelpa 'nyan-mode)
(quelpa 'package-build)
(quelpa 'objc-font-lock)
(quelpa 'pkg-info)
(quelpa 'popwin)
(quelpa 'prodigy)
(quelpa 'projectile)
(quelpa 'quickrun)
(quelpa 's)
(quelpa 'smartparens)
(quelpa 'smex)
(quelpa 'swift-mode)
(quelpa 'use-package)
(quelpa 'visual-regexp)
(quelpa 'web-mode)
(quelpa 'with-editor)
(quelpa 'yasnippet)
